<?php

if ( function_exists( "register_field_group" ) ) {
	register_field_group( array(
		'id'         => 'acf_front-page--welcome',
		'title'      => 'Welcome / Header',
		'fields'     => array(
			array(
				'key'           => 'field_54904d3740746',
				'label'         => 'Title',
				'name'          => 'welcome-title',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => 100,
			),
			array(
				'key'           => 'field_54904d3740747',
				'label'         => 'Subtitle',
				'name'          => 'welcome-subtitle',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => 100,
			),
			array(
				'key'           => 'field_54b7bb60716e9',
				'label'         => 'Quote',
				'name'          => 'welcome-quote',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_54b7bb74716ea',
				'label'         => 'Quotee',
				'name'          => 'welcome-quotee',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_54904d5e40748',
				'label'         => 'Content',
				'name'          => 'welcome-content',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_54904dc440749',
				'label'         => 'Form',
				'name'          => 'welcome-form',
				'type'          => 'acf_cf7',
				'disable'       => array(
					0 => 0,
				),
				'allow_null'    => 1,
				'multiple'      => 0,
				'hide_disabled' => 0,
			),
			array(
				'key'          => 'field_54b7e21061ccc',
				'label'        => 'Background Image',
				'name'         => 'welcome-bg_image',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'default',
			'hide_on_screen' => array(
//				0  => 'permalink',
//				1  => 'the_content',
//				2  => 'excerpt',
//				3  => 'custom_fields',
//				4  => 'discussion',
//				5  => 'comments',
//				6  => 'revisions',
//				7  => 'slug',
//				8  => 'author',
//				9  => 'format',
//				10 => 'featured_image',
//				11 => 'categories',
//				12 => 'tags',
//				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	) );
}

